# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# 参考：https://github.com/JunzhouLiu/BILIBILI-HELPER/actions

name: Log to EDS Every Week

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: 
    # 使用的UTC时间
    # 北京时间=UTC + 8 => UTC = 北京时间 - 8
    # 每周一10:15（北京时间）执行一次
    - cron: '15 2 * * 1'
  workflow_dispatch:

jobs:
  do-eds-log:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        user_id: ${{ secrets.EDS_USER_ID }}
        password: ${{ secrets.EDS_PASSWORD }}
        # 时区设置为上海
        TZ: Asia/Shanghai
      run: mvn compile exec:java -Dexec.mainClass="github.workflow.EDSLogger" -Dexec.args="${user_id} ${password}"
      #run: mvn test -D test="org.young.util.EDSUtilTest"
